

    var availableCity = [
"Nicobar || Andaman and Nicobar Island || India",
"North and Middle Andaman || Andaman and Nicobar Island || India",
"South Andaman || Andaman and Nicobar Island || India",
"Anantapur || Andhra Pradesh || India",
"Chittoor || Andhra Pradesh || India",
"Cuddapah || Andhra Pradesh || India",
"East Godavari || Andhra Pradesh || India",
"Guntur || Andhra Pradesh || India",
"Krishna || Andhra Pradesh || India",
"Kurnool || Andhra Pradesh || India",
"Nellore || Andhra Pradesh || India",
"Prakasam || Andhra Pradesh || India",
"Srikakulam || Andhra Pradesh || India",
"Visakhapatnam || Andhra Pradesh || India",
"Vizianagaram || Andhra Pradesh || India",
"West Godavari || Andhra Pradesh || India",
"Anjaw || Arunachal Pradesh || India",
"Changlang || Arunachal Pradesh || India",
"Dibang Valley || Arunachal Pradesh || India",
"East Kameng || Arunachal Pradesh || India",
"East Siang || Arunachal Pradesh || India",
"Kurung Kumey || Arunachal Pradesh || India",
"Lohit || Arunachal Pradesh || India",
"Longding || Arunachal Pradesh || India",
"Lower Dibang Valley || Arunachal Pradesh || India",
"Lower Subansiri || Arunachal Pradesh || India",
"Papum Pare || Arunachal Pradesh || India",
"Tawang || Arunachal Pradesh || India",
"Tirap || Arunachal Pradesh || India",
"Upper Siang || Arunachal Pradesh || India",
"Upper Subansiri || Arunachal Pradesh || India",
"West Kameng || Arunachal Pradesh || India",
"West Siang || Arunachal Pradesh || India",
"Baksa || Assam || India",
"Barpeta || Assam || India",
"Bongaigaon || Assam || India",
"Cachar || Assam || India",
"Chirang || Assam || India",
"Darrang || Assam || India",
"Dhemaji || Assam || India",
"Dhubri || Assam || India",
"Dibrugarh || Assam || India",
"Dima Hasao || Assam || India",
"Goalpara || Assam || India",
"Golaghat || Assam || India",
"Hailakandi || Assam || India",
"Jorhat || Assam || India",
"Kamrup Metropolitan || Assam || India",
"Kamrup || Assam || India",
"Karbi Anglong || Assam || India",
"Karimganj || Assam || India",
"Kokrajhar || Assam || India",
"Lakhimpur || Assam || India",
"Morigaon || Assam || India",
"Nagaon || Assam || India",
"Nalbari || Assam || India",
"Sivasagar || Assam || India",
"Sonitpur || Assam || India",
"Tinsukia || Assam || India",
"Udalguri || Assam || India",
"Araria || Bihar || India",
"Arwal || Bihar || India",
"Aurangabad || Bihar || India",
"Banka || Bihar || India",
"Begusarai || Bihar || India",
"Bhagalpur || Bihar || India",
"Bhojpur || Bihar || India",
"Buxar || Bihar || India",
"Darbhanga || Bihar || India",
"East Champaran (Motihari) || Bihar || India",
"Gaya || Bihar || India",
"Gopalganj || Bihar || India",
"Jamui || Bihar || India",
"Jehanabad || Bihar || India",
"Kaimur (Bhabua) || Bihar || India",
"Katihar || Bihar || India",
"Khagaria || Bihar || India",
"Kishanganj || Bihar || India",
"Lakhisarai || Bihar || India",
"Madhepura || Bihar || India",
"Madhubani || Bihar || India",
"Munger (Monghyr) || Bihar || India",
"Muzaffarpur || Bihar || India",
"Nalanda || Bihar || India",
"Nawada || Bihar || India",
"Patna || Bihar || India",
"Purnia (Purnea) || Bihar || India",
"Rohtas || Bihar || India",
"Saharsa || Bihar || India",
"Samastipur || Bihar || India",
"Saran || Bihar || India",
"Sheikhpura || Bihar || India",
"Sheohar || Bihar || India",
"Sitamarhi || Bihar || India",
"Siwan || Bihar || India",
"Supaul || Bihar || India",
"Vaishali || Bihar || India",
"West Champaran || Bihar || India",
"Chandigarh || Chandigarh || India",
"Balod || Chhattisgarh || India",
"Baloda Bazar || Chhattisgarh || India",
"Balrampur || Chhattisgarh || India",
"Bastar || Chhattisgarh || India",
"Bemetara || Chhattisgarh || India",
"Bijapur || Chhattisgarh || India",
"Bilaspur || Chhattisgarh || India",
"Dantewada (South Bastar) || Chhattisgarh || India",
"Dhamtari || Chhattisgarh || India",
"Durg || Chhattisgarh || India",
"Gariaband || Chhattisgarh || India",
"Janjgir-Champa || Chhattisgarh || India",
"Jashpur || Chhattisgarh || India",
"Kabirdham (Kawardha) || Chhattisgarh || India",
"Kanker (North Bastar) || Chhattisgarh || India",
"Kondagaon || Chhattisgarh || India",
"Korba || Chhattisgarh || India",
"Korea (Koriya) || Chhattisgarh || India",
"Mahasamund || Chhattisgarh || India",
"Mungeli || Chhattisgarh || India",
"Narayanpur || Chhattisgarh || India",
"Raigarh || Chhattisgarh || India",
"Raipur || Chhattisgarh || India",
"Rajnandgaon || Chhattisgarh || India",
"Sukma || Chhattisgarh || India",
"Surajpur || Chhattisgarh || India",
"Surguja || Chhattisgarh || India",
"Dadra & Nagar Haveli || Dadra and Nagar Haveli || India",
"Daman || Daman and Diu || India",
"Diu || Daman and Diu || India",
"Central Delhi || Delhi || India",
"East Delhi || Delhi || India",
"New Delhi || Delhi || India",
"North Delhi || Delhi || India",
"North East Delhi || Delhi || India",
"North West Delhi || Delhi || India",
"South Delhi || Delhi || India",
"South West Delhi || Delhi || India",
"West Delhi || Delhi || India",
"North Goa || Goa || India",
"South Goa || Goa || India",
"Ahmedabad || Gujarat || India",
"Amreli || Gujarat || India",
"Anand || Gujarat || India",
"Aravalli || Gujarat || India",
"Banaskantha (Palanpur) || Gujarat || India",
"Bharuch || Gujarat || India",
"Bhavnagar || Gujarat || India",
"Botad || Gujarat || India",
"Chhota Udepur || Gujarat || India",
"Dahod || Gujarat || India",
"Dangs (Ahwa) || Gujarat || India",
"Devbhoomi Dwarka || Gujarat || India",
"Gandhinagar || Gujarat || India",
"Gir Somnath || Gujarat || India",
"Jamnagar || Gujarat || India",
"Junagadh || Gujarat || India",
"Kachchh || Gujarat || India",
"Kheda (Nadiad) || Gujarat || India",
"Mahisagar || Gujarat || India",
"Mehsana || Gujarat || India",
"Morbi || Gujarat || India",
"Narmada (Rajpipla) || Gujarat || India",
"Navsari || Gujarat || India",
"Panchmahal (Godhra) || Gujarat || India",
"Patan || Gujarat || India",
"Porbandar || Gujarat || India",
"Rajkot || Gujarat || India",
"Sabarkantha (Himmatnagar) || Gujarat || India",
"Surat || Gujarat || India",
"Surendranagar || Gujarat || India",
"Tapi (Vyara) || Gujarat || India",
"Vadodara || Gujarat || India",
"Valsad || Gujarat || India",
"Ambala || Haryana || India",
"Bhiwani || Haryana || India",
"Faridabad || Haryana || India",
"Fatehabad || Haryana || India",
"Gurgaon || Haryana || India",
"Hisar || Haryana || India",
"Jhajjar || Haryana || India",
"Jind || Haryana || India",
"Kaithal || Haryana || India",
"Karnal || Haryana || India",
"Kurukshetra || Haryana || India",
"Mahendragarh || Haryana || India",
"Mewat || Haryana || India",
"Palwal || Haryana || India",
"Panchkula || Haryana || India",
"Panipat || Haryana || India",
"Rewari || Haryana || India",
"Rohtak || Haryana || India",
"Sirsa || Haryana || India",
"Sonipat || Haryana || India",
"Yamunanagar || Haryana || India",
"Bilaspur || Himachal Pradesh || India",
"Chamba || Himachal Pradesh || India",
"Hamirpur || Himachal Pradesh || India",
"Kangra || Himachal Pradesh || India",
"Kinnaur || Himachal Pradesh || India",
"Kullu || Himachal Pradesh || India",
"Lahaul & Spiti || Himachal Pradesh || India",
"Mandi || Himachal Pradesh || India",
"Shimla || Himachal Pradesh || India",
"Sirmaur (Sirmour) || Himachal Pradesh || India",
"Solan || Himachal Pradesh || India",
"Una || Himachal Pradesh || India",
"Anantnag || Jammu and Kashmir || India",
"Bandipora || Jammu and Kashmir || India",
"Baramulla || Jammu and Kashmir || India",
"Budgam || Jammu and Kashmir || India",
"Doda || Jammu and Kashmir || India",
"Ganderbal || Jammu and Kashmir || India",
"Jammu || Jammu and Kashmir || India",
"Kargil || Jammu and Kashmir || India",
"Kathua || Jammu and Kashmir || India",
"Kishtwar || Jammu and Kashmir || India",
"Kulgam || Jammu and Kashmir || India",
"Kupwara || Jammu and Kashmir || India",
"Leh || Jammu and Kashmir || India",
"Poonch || Jammu and Kashmir || India",
"Pulwama || Jammu and Kashmir || India",
"Rajouri || Jammu and Kashmir || India",
"Ramban || Jammu and Kashmir || India",
"Reasi || Jammu and Kashmir || India",
"Samba || Jammu and Kashmir || India",
"Shopian || Jammu and Kashmir || India",
"Srinagar || Jammu and Kashmir || India",
"Udhampur || Jammu and Kashmir || India",
"Bokaro || Jharkhand || India",
"Chatra || Jharkhand || India",
"Deoghar || Jharkhand || India",
"Dhanbad || Jharkhand || India",
"Dumka || Jharkhand || India",
"East Singhbhum || Jharkhand || India",
"Garhwa || Jharkhand || India",
"Giridih || Jharkhand || India",
"Godda || Jharkhand || India",
"Gumla || Jharkhand || India",
"Hazaribag || Jharkhand || India",
"Jamtara || Jharkhand || India",
"Khunti || Jharkhand || India",
"Koderma || Jharkhand || India",
"Latehar || Jharkhand || India",
"Lohardaga || Jharkhand || India",
"Pakur || Jharkhand || India",
"Palamu || Jharkhand || India",
"Ramgarh || Jharkhand || India",
"Ranchi || Jharkhand || India",
"Sahibganj || Jharkhand || India",
"Seraikela-Kharsawan || Jharkhand || India",
"Simdega || Jharkhand || India",
"West Singhbhum || Jharkhand || India",
"Bagalkot || Karnataka || India",
"Bangalore Rural || Karnataka || India",
"Bangalore Urban || Karnataka || India",
"Belgaum || Karnataka || India",
"Bellary || Karnataka || India",
"Bidar || Karnataka || India",
"Bijapur || Karnataka || India",
"Chamarajanagar || Karnataka || India",
"Chickmagalur || Karnataka || India",
"Chikballapur || Karnataka || India",
"Chitradurga || Karnataka || India",
"Dakshina Kannada || Karnataka || India",
"Davangere || Karnataka || India",
"Dharwad || Karnataka || India",
"Gadag || Karnataka || India",
"Gulbarga || Karnataka || India",
"Hassan || Karnataka || India",
"Haveri || Karnataka || India",
"Kodagu || Karnataka || India",
"Kolar || Karnataka || India",
"Koppal || Karnataka || India",
"Mandya || Karnataka || India",
"Mysore || Karnataka || India",
"Raichur || Karnataka || India",
"Ramnagara || Karnataka || India",
"Shimoga || Karnataka || India",
"Tumkur || Karnataka || India",
"Udupi || Karnataka || India",
"Uttara Kannada (Karwar) || Karnataka || India",
"Yadgir || Karnataka || India",
"Alappuzha || Kerala || India",
"Ernakulam || Kerala || India",
"Idukki || Kerala || India",
"Kannur || Kerala || India",
"Kasaragod || Kerala || India",
"Kollam || Kerala || India",
"Kottayam || Kerala || India",
"Kozhikode || Kerala || India",
"Malappuram || Kerala || India",
"Palakkad || Kerala || India",
"Pathanamthitta || Kerala || India",
"Thiruvananthapuram || Kerala || India",
"Thrissur || Kerala || India",
"Wayanad || Kerala || India",
"Lakshadweep || Lakshadweep || India",
"Alirajpur || Madhya Pradesh || India",
"Anuppur || Madhya Pradesh || India",
"Ashoknagar || Madhya Pradesh || India",
"Balaghat || Madhya Pradesh || India",
"Barwani || Madhya Pradesh || India",
"Betul || Madhya Pradesh || India",
"Bhind || Madhya Pradesh || India",
"Bhopal || Madhya Pradesh || India",
"Burhanpur || Madhya Pradesh || India",
"Chhatarpur || Madhya Pradesh || India",
"Chhindwara || Madhya Pradesh || India",
"Damoh || Madhya Pradesh || India",
"Datia || Madhya Pradesh || India",
"Dewas || Madhya Pradesh || India",
"Dhar || Madhya Pradesh || India",
"Dindori || Madhya Pradesh || India",
"Guna || Madhya Pradesh || India",
"Gwalior || Madhya Pradesh || India",
"Harda || Madhya Pradesh || India",
"Hoshangabad || Madhya Pradesh || India",
"Indore || Madhya Pradesh || India",
"Jabalpur || Madhya Pradesh || India",
"Jhabua || Madhya Pradesh || India",
"Katni || Madhya Pradesh || India",
"Khandwa || Madhya Pradesh || India",
"Khargone || Madhya Pradesh || India",
"Mandla || Madhya Pradesh || India",
"Mandsaur || Madhya Pradesh || India",
"Morena || Madhya Pradesh || India",
"Narsinghpur || Madhya Pradesh || India",
"Neemuch || Madhya Pradesh || India",
"Panna || Madhya Pradesh || India",
"Raisen || Madhya Pradesh || India",
"Rajgarh || Madhya Pradesh || India",
"Ratlam || Madhya Pradesh || India",
"Rewa || Madhya Pradesh || India",
"Sagar || Madhya Pradesh || India",
"Satna || Madhya Pradesh || India",
"Sehore || Madhya Pradesh || India",
"Seoni || Madhya Pradesh || India",
"Shahdol || Madhya Pradesh || India",
"Shajapur || Madhya Pradesh || India",
"Sheopur || Madhya Pradesh || India",
"Shivpuri || Madhya Pradesh || India",
"Sidhi || Madhya Pradesh || India",
"Singrauli || Madhya Pradesh || India",
"Tikamgarh || Madhya Pradesh || India",
"Ujjain || Madhya Pradesh || India",
"Umaria || Madhya Pradesh || India",
"Vidisha || Madhya Pradesh || India",
"Ahmednagar || Maharashtra || India",
"Akola || Maharashtra || India",
"Amravati || Maharashtra || India",
"Aurangabad || Maharashtra || India",
"Beed || Maharashtra || India",
"Bhandara || Maharashtra || India",
"Buldhana || Maharashtra || India",
"Chandrapur || Maharashtra || India",
"Dhule || Maharashtra || India",
"Gadchiroli || Maharashtra || India",
"Gondia || Maharashtra || India",
"Hingoli || Maharashtra || India",
"Jalgaon || Maharashtra || India",
"Jalna || Maharashtra || India",
"Kolhapur || Maharashtra || India",
"Latur || Maharashtra || India",
"Mumbai City || Maharashtra || India",
"Mumbai Suburban || Maharashtra || India",
"Nagpur || Maharashtra || India",
"Nanded || Maharashtra || India",
"Nandurbar || Maharashtra || India",
"Nashik || Maharashtra || India",
"Osmanabad || Maharashtra || India",
"Parbhani || Maharashtra || India",
"Pune || Maharashtra || India",
"Raigad || Maharashtra || India",
"Ratnagiri || Maharashtra || India",
"Sangli || Maharashtra || India",
"Satara || Maharashtra || India",
"Sindhudurg || Maharashtra || India",
"Solapur || Maharashtra || India",
"Thane || Maharashtra || India",
"Wardha || Maharashtra || India",
"Washim || Maharashtra || India",
"Yavatmal || Maharashtra || India",
"Bishnupur || Manipur || India",
"Chandel || Manipur || India",
"Churachandpur || Manipur || India",
"Imphal East || Manipur || India",
"Imphal West || Manipur || India",
"Senapati || Manipur || India",
"Tamenglong || Manipur || India",
"Thoubal || Manipur || India",
"Ukhrul || Manipur || India",
"East Garo Hills || Meghalaya || India",
"East Jaintia Hills || Meghalaya || India",
"East Khasi Hills || Meghalaya || India",
"North Garo Hills || Meghalaya || India",
"Ri Bhoi || Meghalaya || India",
"South Garo Hills || Meghalaya || India",
"South West Garo Hills || Meghalaya || India",
"South West Khasi Hills || Meghalaya || India",
"West Garo Hills || Meghalaya || India",
"West Jaintia Hills || Meghalaya || India",
"West Khasi Hills || Meghalaya || India",
"Aizawl || Mizoram || India",
"Champhai || Mizoram || India",
"Kolasib || Mizoram || India",
"Lawngtlai || Mizoram || India",
"Lunglei || Mizoram || India",
"Mamit || Mizoram || India",
"Saiha || Mizoram || India",
"Serchhip || Mizoram || India",
"Dimapur || Nagaland || India",
"Kiphire || Nagaland || India",
"Kohima || Nagaland || India",
"Longleng || Nagaland || India",
"Mokokchung || Nagaland || India",
"Mon || Nagaland || India",
"Peren || Nagaland || India",
"Phek || Nagaland || India",
"Tuensang || Nagaland || India",
"Wokha || Nagaland || India",
"Zunheboto || Nagaland || India",
"Angul || Odisha || India",
"Balangir || Odisha || India",
"Balasore || Odisha || India",
"Bargarh || Odisha || India",
"Bhadrak || Odisha || India",
"Boudh || Odisha || India",
"Cuttack || Odisha || India",
"Deogarh || Odisha || India",
"Dhenkanal || Odisha || India",
"Gajapati || Odisha || India",
"Ganjam || Odisha || India",
"Jagatsinghapur || Odisha || India",
"Jajpur || Odisha || India",
"Jharsuguda || Odisha || India",
"Kalahandi || Odisha || India",
"Kandhamal || Odisha || India",
"Kendrapara || Odisha || India",
"Kendujhar (Keonjhar) || Odisha || India",
"Khordha || Odisha || India",
"Koraput || Odisha || India",
"Malkangiri || Odisha || India",
"Mayurbhanj || Odisha || India",
"Nabarangpur || Odisha || India",
"Nayagarh || Odisha || India",
"Nuapada || Odisha || India",
"Puri || Odisha || India",
"Rayagada || Odisha || India",
"Sambalpur || Odisha || India",
"Sonepur || Odisha || India",
"Sundargarh || Odisha || India",
"Karaikal || Puducherry || India",
"Mahe || Puducherry || India",
"Pondicherry || Puducherry || India",
"Yanam || Puducherry || India",
"Amritsar || Punjab || India",
"Barnala || Punjab || India",
"Bathinda || Punjab || India",
"Faridkot || Punjab || India",
"Fatehgarh Sahib || Punjab || India",
"Fazilka || Punjab || India",
"Ferozepur || Punjab || India",
"Gurdaspur || Punjab || India",
"Hoshiarpur || Punjab || India",
"Jalandhar || Punjab || India",
"Kapurthala || Punjab || India",
"Ludhiana || Punjab || India",
"Mansa || Punjab || India",
"Moga || Punjab || India",
"Muktsar || Punjab || India",
"Nawanshahr || Punjab || India",
"Pathankot || Punjab || India",
"Patiala || Punjab || India",
"Rupnagar || Punjab || India",
"Sangrur || Punjab || India",
"SAS Nagar (Mohali) || Punjab || India",
"Tarn Taran || Punjab || India",
"Ajmer || Rajasthan || India",
"Alwar || Rajasthan || India",
"Banswara || Rajasthan || India",
"Baran || Rajasthan || India",
"Barmer || Rajasthan || India",
"Bharatpur || Rajasthan || India",
"Bhilwara || Rajasthan || India",
"Bikaner || Rajasthan || India",
"Bundi || Rajasthan || India",
"Chittorgarh || Rajasthan || India",
"Churu || Rajasthan || India",
"Dausa || Rajasthan || India",
"Dholpur || Rajasthan || India",
"Dungarpur || Rajasthan || India",
"Hanumangarh || Rajasthan || India",
"Jaipur || Rajasthan || India",
"Jaisalmer || Rajasthan || India",
"Jalore || Rajasthan || India",
"Jhalawar || Rajasthan || India",
"Jhunjhunu || Rajasthan || India",
"Jodhpur || Rajasthan || India",
"Karauli || Rajasthan || India",
"Kota || Rajasthan || India",
"Nagaur || Rajasthan || India",
"Pali || Rajasthan || India",
"Pratapgarh || Rajasthan || India",
"Rajsamand || Rajasthan || India",
"Sawai Madhopur || Rajasthan || India",
"Sikar || Rajasthan || India",
"Sirohi || Rajasthan || India",
"Sri Ganganagar || Rajasthan || India",
"Tonk || Rajasthan || India",
"Udaipur || Rajasthan || India",
"East Sikkim || Sikkim || India",
"North Sikkim || Sikkim || India",
"South Sikkim || Sikkim || India",
"West Sikkim || Sikkim || India",
"Ariyalur || Tamil Nadu || India",
"Chennai || Tamil Nadu || India",
"Coimbatore || Tamil Nadu || India",
"Cuddalore || Tamil Nadu || India",
"Dharmapuri || Tamil Nadu || India",
"Dindigul || Tamil Nadu || India",
"Erode || Tamil Nadu || India",
"Kanchipuram || Tamil Nadu || India",
"Kanyakumari || Tamil Nadu || India",
"Karur || Tamil Nadu || India",
"Krishnagiri || Tamil Nadu || India",
"Madurai || Tamil Nadu || India",
"Nagapattinam || Tamil Nadu || India",
"Namakkal || Tamil Nadu || India",
"Nilgiris || Tamil Nadu || India",
"Perambalur || Tamil Nadu || India",
"Pudukkottai || Tamil Nadu || India",
"Ramanathapuram || Tamil Nadu || India",
"Salem || Tamil Nadu || India",
"Sivaganga || Tamil Nadu || India",
"Thanjavur || Tamil Nadu || India",
"Theni || Tamil Nadu || India",
"Thoothukudi (Tuticorin) || Tamil Nadu || India",
"Tiruchirappalli || Tamil Nadu || India",
"Tirunelveli || Tamil Nadu || India",
"Tiruppur || Tamil Nadu || India",
"Tiruvallur || Tamil Nadu || India",
"Tiruvannamalai || Tamil Nadu || India",
"Tiruvarur || Tamil Nadu || India",
"Vellore || Tamil Nadu || India",
"Viluppuram || Tamil Nadu || India",
"Virudhunagar || Tamil Nadu || India",
"Adilabad || Telangana || India",
"Hyderabad || Telangana || India",
"Karimnagar || Telangana || India",
"Khammam || Telangana || India",
"Mahabubnagar || Telangana || India",
"Medak || Telangana || India",
"Nalgonda || Telangana || India",
"Nizamabad || Telangana || India",
"Rangareddy || Telangana || India",
"Warangal || Telangana || India",
"Dhalai || Tripura || India",
"Gomati || Tripura || India",
"Khowai || Tripura || India",
"North Tripura || Tripura || India",
"Sepahijala || Tripura || India",
"South Tripura || Tripura || India",
"Unakoti || Tripura || India",
"West Tripura || Tripura || India",
"Agra || Uttar Pradesh || India",
"Aligarh || Uttar Pradesh || India",
"Allahabad || Uttar Pradesh || India",
"Ambedkar Nagar || Uttar Pradesh || India",
"Auraiya || Uttar Pradesh || India",
"Azamgarh || Uttar Pradesh || India",
"Baghpat || Uttar Pradesh || India",
"Bahraich || Uttar Pradesh || India",
"Ballia || Uttar Pradesh || India",
"Balrampur || Uttar Pradesh || India",
"Banda || Uttar Pradesh || India",
"Barabanki || Uttar Pradesh || India",
"Bareilly || Uttar Pradesh || India",
"Basti || Uttar Pradesh || India",
"Sambhal (Bhim Nagar) || Uttar Pradesh || India",
"Bijnor || Uttar Pradesh || India",
"Budaun || Uttar Pradesh || India",
"Bulandshahr || Uttar Pradesh || India",
"Chandauli || Uttar Pradesh || India",
"Amethi (Chatrapati Sahuji Mahraj Nagar) || Uttar Pradesh || India",
"Chitrakoot || Uttar Pradesh || India",
"Deoria || Uttar Pradesh || India",
"Etah || Uttar Pradesh || India",
"Etawah || Uttar Pradesh || India",
"Faizabad || Uttar Pradesh || India",
"Farrukhabad || Uttar Pradesh || India",
"Fatehpur || Uttar Pradesh || India",
"Firozabad || Uttar Pradesh || India",
"Gautam Buddha Nagar || Uttar Pradesh || India",
"Ghaziabad || Uttar Pradesh || India",
"Ghazipur || Uttar Pradesh || India",
"Gonda || Uttar Pradesh || India",
"Gorakhpur || Uttar Pradesh || India",
"Hamirpur || Uttar Pradesh || India",
"Hardoi || Uttar Pradesh || India",
"Hathras || Uttar Pradesh || India",
"Jalaun || Uttar Pradesh || India",
"Jaunpur || Uttar Pradesh || India",
"Jhansi || Uttar Pradesh || India",
"Amroha (J.P. Nagar) || Uttar Pradesh || India",
"Kannauj || Uttar Pradesh || India",
"Kanpur Dehat || Uttar Pradesh || India",
"Kanpur Nagar || Uttar Pradesh || India",
"Kanshiram Nagar || Uttar Pradesh || India",
"Kaushambi || Uttar Pradesh || India",
"Kushinagar  || Uttar Pradesh || India",
"Lakhimpur - Kheri || Uttar Pradesh || India",
"Lalitpur || Uttar Pradesh || India",
"Lucknow || Uttar Pradesh || India",
"Maharajganj || Uttar Pradesh || India",
"Mahoba || Uttar Pradesh || India",
"Mainpuri || Uttar Pradesh || India",
"Mathura || Uttar Pradesh || India",
"Mau || Uttar Pradesh || India",
"Meerut || Uttar Pradesh || India",
"Mirzapur || Uttar Pradesh || India",
"Moradabad || Uttar Pradesh || India",
"Muzaffarnagar || Uttar Pradesh || India",
"Hapur (Panchsheel Nagar) || Uttar Pradesh || India",
"Pilibhit || Uttar Pradesh || India",
"Shamali (Prabuddh Nagar) || Uttar Pradesh || India",
"Pratapgarh || Uttar Pradesh || India",
"RaeBareli || Uttar Pradesh || India",
"Rampur || Uttar Pradesh || India",
"Saharanpur || Uttar Pradesh || India",
"Sant Kabir Nagar || Uttar Pradesh || India",
"Sant Ravidas Nagar || Uttar Pradesh || India",
"Shahjahanpur || Uttar Pradesh || India",
"Shravasti || Uttar Pradesh || India",
"Siddharth Nagar || Uttar Pradesh || India",
"Sitapur || Uttar Pradesh || India",
"Sonbhadra || Uttar Pradesh || India",
"Sultanpur || Uttar Pradesh || India",
"Unnao || Uttar Pradesh || India",
"Varanasi || Uttar Pradesh || India",
"Almora || Uttarakhand || India",
"Bageshwar || Uttarakhand || India",
"Chamoli || Uttarakhand || India",
"Champawat || Uttarakhand || India",
"Dehradun || Uttarakhand || India",
"Haridwar || Uttarakhand || India",
"Nainital || Uttarakhand || India",
"Pauri Garhwal || Uttarakhand || India",
"Pithoragarh || Uttarakhand || India",
"Rudraprayag || Uttarakhand || India",
"Tehri Garhwal || Uttarakhand || India",
"Udham Singh Nagar || Uttarakhand || India",
"Uttarkashi || Uttarakhand || India",
"Bankura || West Bengal || India",
"Birbhum || West Bengal || India",
"Burdwan (Bardhaman) || West Bengal || India",
"Cooch Behar || West Bengal || India",
"Dakshin Dinajpur (South Dinajpur) || West Bengal || India",
"Darjeeling || West Bengal || India",
"Hooghly || West Bengal || India",
"Howrah || West Bengal || India",
"Jalpaiguri || West Bengal || India",
"Kolkata || West Bengal || India",
"Malda || West Bengal || India",
"Murshidabad || West Bengal || India",
"Nadia || West Bengal || India",
"North 24 Parganas || West Bengal || India",
"Paschim Medinipur (West Medinipur) || West Bengal || India",
"Purba Medinipur (East Medinipur) || West Bengal || India",
"Purulia || West Bengal || India",
"South 24 Parganas || West Bengal || India",
"Uttar Dinajpur (North Dinajpur) || West Bengal || India",
"Jammu || Jammu and Kashmir|| India",
"Sunderbani || Jammu and Kashmir|| India",
 ];
